### ISSUE TITLE
Displaying object's strengths

### ISSUE THREAD

**Issue by LifeAlgorithm** [LifeAlgorithm/RockPaperScissors#7]
Do we want to display object strengths in rounds? We decided last Tuesday to get rid of displaying strengths, but I noticed while testing that it still appears when the user chooses rock or paper. Those can easily be deleted, but on second thought, would it actually be useful to display these strengths? Or should we just leave them out?

**Comment by huarngpa** [comment]
I'd prefer to just leave them in...

**Comment by chews93319** [comment]
I prefer to display the information on the screen.
Unless instructions tell me to specifically not share information with the
user in the console, then I tend to put out all the status and event
information.

Sam

**Comment by LifeAlgorithm** [comment]
Ok, let's add it back in for scissors. I think we can also make the messages more dynamic. Instead of object1 and object2, we can use the longtypes that Peter introduced to make it say "{Insert Tool name} strength: 100", where insert tool name is Rock, Paper, and Scissors.

**Comment by chews93319** [comment]
I'm looking at the Round Results right now and also think that the Strengths should print out the 'tempStrength' as well as the original strength. I'm going to add it in and try it out. I'll also add the longTypes.

**Comment by pyetti** [comment]
Hi guys,

My test is actually at 8:30, not 7. I'm sorry about that. I can meet after
if you want, or tomorrow.
